name: "Send Metrics"
description: "Send metrics to API Rest Service"
inputs:
  url:
    description: "URL to send metrics"
    required: true
  token:
    description: "Token to send metrics"
    required: true
  repo_owner:
    description: "Repository owner"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "TIMESTAMP='$(date --iso-8601=seconds)'" >> $GITHUB_ENV
      shell: bash
    - run: |
        curl --location '${{ inputs.url }}'' \
          --header 'Content-Type: application/json' \
          --header 'APIKEY: '${{ inputs.token }}'' \
          --data '{
          "timestamp": "'$TIMESTAMP'",
          "repository": "${{ github.github_server_url }}/${{ github.repository }}",
          "repo_owner": "${{ inputs.repo_owner }}",
          "branch": "${{ github.ref }}",
          "commit": "${{ github.sha }}",
          "executed_control": "${{ github.workflow }}",
          "control_result": "Success",
          "control_output": "Control success",
          "job_url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
        }'
      shell: bash
