name: "Send Metrics"
description: "Send metrics to API Rest Service"
inputs:
  url:
    description: "URL to send metrics"
    required: true
  token:
    description: "Token to send metrics"
    required: true
  repo_owner:
    description: "Repository owner"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cURL
      run: sudo apt-get update && sudo apt-get install -y curl
      shell: bash
    - name: "Set up environment"
      shell: bash
      run: |
        echo "URL=${{ inputs.url }}" >> $GITHUB_ENV
        echo "TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date --iso-8601=seconds)" >> $GITHUB_ENV
        echo "REPOSITORY=${{ github.github_server_url }}/${{ github.repository }}" >> $GITHUB_ENV
        echo "REPO_OWNER=${{ inputs.repo_owner }}" >> $GITHUB_ENV
        echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
        echo "COMMIT=${{ github.sha }}" >> $GITHUB_ENV
        echo "EXECUTED_CONTROL=${{ github.workflow }}" >> $GITHUB_ENV
        echo "CONTROL_RESULT=success" >> $GITHUB_ENV
        echo "CONTROL_OUTPUT='Control success'" >> $GITHUB_ENV
        echo "JOB_URL=${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
    - name: "Send metrics"
      run: send-metrics.sh
      shell: bash
